name: Keyboard-Cowboy
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: "11.0"
  preGenCommand: "sh XcodeGen/preGenCommand.sh"
  postGenCommand: "sh XcodeGen/postGenCommand.sh"
configFiles:
  Debug: XcodeGen/Debug.xcconfig
  Release: XcodeGen/Release.xcconfig
packages:
  DirectoryObserver:
    url: https://github.com/zenangst/DirectoryObserver
    branch: main
  LaunchArguments:
    url: https://github.com/zenangst/LaunchArguments
    branch: main
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: 1.8.2
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    revision: "891afd44c7075e699924ed9b81d8dc94a5111dfd"
  Introspect:
    url: https://github.com/siteline/SwiftUI-Introspect
    from: 0.1.2
  MbSwiftUIFirstResponder:
    url: https://github.com/mobilinked/MbSwiftUIFirstResponder
    branch: main
targets:
  Keyboard-Cowboy:
    type: application
    platform: "macOS"
    dependencies:
      - target: BridgeKit
      - target: ModelKit
      - target: ViewKit
      - target: LogicFramework
      - package: DirectoryObserver
      - package: LaunchArguments
      - package: Sparkle
    sources:
      - App
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        CODE_SIGN_IDENTITY: "-"
        CURRENT_PROJECT_VERSION: 71
        INFOPLIST_FILE: "App/Resources/Info.plist"
        MARKETING_VERSION: 0.14.0
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy"
        PRODUCT_NAME: "Keyboard Cowboy"
        ENABLE_HARDENED_RUNTIME: true
    preBuildScripts:
      - path: XcodeGen/Scripts/swiftlint.sh
        name: SwiftLint
    postBuildScripts:
      - path: XcodeGen/Scripts/generate_release_env.sh
        name: Generate release environment
    entitlements:
      path: App/Resources/com.zenangst.Keyboard-Cowboy.entitlements
      properties:
        com.apple.security.automation.apple-events: true
  UnitTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: UnitTests
        includes:
          - Sources
        excludes:
          - Sources/Models/__Snapshots__
          - Sources/Views/__Snapshots__
    scheme: {}
    dependencies:
      - target: Keyboard-Cowboy
      - package: SnapshotTesting
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.UnitTests"
      TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Keyboard Cowboy.app/Contents/MacOS/Keyboard Cowboy"
  BridgeKit:
    type: framework
    platform: "macOS"
    dependencies:
      - target: ModelKit
    sources:
      - BridgeKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy.BridgeKit"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "BridgeKit/Resources/Info.plist"
  LogicFramework:
    type: framework
    platform: "macOS"
    dependencies:
      - target: BridgeKit
      - target: ModelKit
    sources:
      - LogicFramework
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy.Logic"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "LogicFramework/Resources/Info.plist"
  ModelKit:
    type: framework
    platform: "macOS"
    sources:
      - ModelKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy.ModelKit"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "ModelKit/Resources/Info.plist"
  ViewKit:
    type: framework
    platform: "macOS"
    dependencies:
      - target: BridgeKit
      - target: ModelKit
      - package: Introspect
      - package: MbSwiftUIFirstResponder
    sources:
      - ViewKit
      - Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy.ViewKit"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "ViewKit/Resources/Info.plist"
schemes:
  Keyboard-Cowboy:
    build:
      targets:
        Keyboard-Cowboy: all
    run:
      config: Debug
      commandLineArguments:
        "-open-window-at-launch": true
        "-demo-mode": true
        "-disable-keyboard-shortcuts": true
        "-debug": false
      environmentVariables:
        SOURCE_ROOT: $(SRCROOT)
    test:
      config: Debug
      commandLineArguments:
        "-running-unit-tests": true
      gatherCoverageData: true
      coverageTargets:
        - Keyboard-Cowboy
        - LogicFramework
        - ViewKit
      targets:
        - name: UnitTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false
fileGroups:
  - .github
  - .gitignore
  - .swiftlint.yml
  - create_release.sh
  - appcast.xml
  - keyboard-cowboy.json
  - README.md
  - XcodeGen
  - project.yml
  - Scripts
  - UnitTests/Sources/Views/__Snapshots__
