name: Keyboard-Cowboy
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: "10.15"
  preGenCommand: "sh XcodeGen/preGenCommand.sh"
  postGenCommand: "sh XcodeGen/postGenCommand.sh"
configFiles:
  Debug: XcodeGen/Debug.xcconfig
  Release: XcodeGen/Release.xcconfig
packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    from: 1.8.2
targets:
  Keyboard-Cowboy:
    type: application
    platform: "macOS"
    dependencies:
      - target: ViewKit
      - target: LogicFramework
    sources:
      - App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy"
        MARKETING_VERSION: 0.0.1
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "App/Resources/Info.plist"
        CODE_SIGN_IDENTITY: "-"
        EXCLUDED_ARCHS: "arm64"
    preBuildScripts:
      - path: XcodeGen/Scripts/swiftlint.sh
        name: SwiftLint
    entitlements:
      path: App/Resources/com.zenangst.Keyboard-Cowboy.entitlements
      properties:
        com.apple.security.automation.apple-events: true
  UnitTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: UnitTests
        includes:
          - Sources
        excludes:
          - Sources/Models/__Snapshots__
          - Sources/Views/__Snapshots__
    scheme: {}
    dependencies:
      - target: Keyboard-Cowboy
      - package: SnapshotTesting
    settings:
      BUNDLE_LOADER: $(TEST_HOST)
      PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.UnitTests"
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Keyboard-Cowboy.app/Contents/MacOS/Keyboard-Cowboy
      EXCLUDED_ARCHS: "arm64"
  LogicFramework:
    type: framework
    platform: "macOS"
    sources:
      - LogicFramework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy.Logic"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "LogicFramework/Resources/Info.plist"
        EXCLUDED_ARCHS: "arm64"
  ViewKit:
    type: framework
    platform: "macOS"
    sources:
      - ViewKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Keyboard-Cowboy.ViewKit"
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: "ViewKit/Resources/Info.plist"
        EXCLUDED_ARCHS: "arm64"
schemes:
  Keyboard-Cowboy:
    build:
      targets:
        Keyboard-Cowboy: all
    run:
      config: Debug
      environmentVariables:
        SOURCE_ROOT: $(SRCROOT)
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Keyboard-Cowboy
        - LogicFramework
        - ViewKit
      targets:
        - name: UnitTests
          parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false
fileGroups:
  - .github
  - .gitignore
  - .swiftlint.yml
  - README.md
  - XcodeGen
  - project.yml
