typealias ConfigurationPublisher = ViewModelsPublisher<ConfigurationViewModel>
typealias GroupsPublisher = ViewModelsPublisher<GroupViewModel>
typealias GroupPublisher = ViewModelPublisher<GroupViewModel>
typealias ContentPublisher = ViewModelsPublisher<ContentViewModel>
typealias DetailStatePublisher = ViewModelPublisher<DetailViewState>
typealias DetailPublisher = ViewModelPublisher<DetailViewModel>
typealias BezelNotificationPublisher = ViewModelPublisher<BezelNotificationViewModel>
typealias WorkflowNotificationPublisher = ViewModelPublisher<WorkflowNotificationViewModel>

