import Foundation

public final class FileIndexPatternsFactory {
  // swiftlint:disable function_body_length
  public static func patterns() -> [FileIndexPattern] {
    [
      .ignorePattern("/Applications/Adobe Photoshop 2020"),
      .ignorePattern("/Library/Apple/"),
      .ignorePattern("/Library/Application Support/"),
      .ignorePattern("/Library/Backblaze/"),
      .ignorePattern("/Library/Developer/"),
      .ignorePattern("/Library/Image Capture"),
      .ignorePattern("/Library/Java/"),
      .ignorePattern("/Library/Perl/"),
      .ignorePattern("/Library/Printers/"),
      .ignorePattern("/Library/Ruby/"),
      .ignorePattern("/Library/Webserver/"),
      .ignorePattern("/System/Library/Accessibility/"),
      .ignorePattern("/System/Library/AccessibilityBundles/"),
      .ignorePattern("/System/Library/Accounts/"),
      .ignorePattern("/System/Library/AssetsV2/"),
      .ignorePattern("/System/Library/Assistant/"),
      .ignorePattern("/System/Library/Audio/"),
      .ignorePattern("/System/Library/Automator/"),
      .ignorePattern("/System/Library/Colors/"),
      .ignorePattern("/System/Library/Components/"),
      .ignorePattern("/System/Library/Compositions/"),
      .ignorePattern("/System/Library/ConfigurationProfiles/"),
      .ignorePattern("/System/Library/CoreServices/Encodings/"),
      .ignorePattern("/System/Library/CoreServices/Menu Extras/"),
      .ignorePattern("/System/Library/CoreServices/Resources/"),
      .ignorePattern("/System/Library/CoreServices/SetupAssistantPlugins/"),
      .ignorePattern("/System/Library/CoreServices/UAUPlugins/"),
      .ignorePattern("/System/Library/Displays/"),
      .ignorePattern("/System/Library/DistributedEvaluation/"),
      .ignorePattern("/System/Library/DriverExtensions/"),
      .ignorePattern("/System/Library/Extensions/"),
      .ignorePattern("/System/Library/Fonts/"),
      .ignorePattern("/System/Library/Frameworks/"),
      .ignorePattern("/System/Library/HIDPlugins/"),
      .ignorePattern("/System/Library/KerberosPlugins/"),
      .ignorePattern("/System/Library/LocationBundles/"),
      .ignorePattern("/System/Library/LoginPlugins/"),
      .ignorePattern("/System/Library/Messages/"),
      .ignorePattern("/System/Library/MonitorPanels/"),
      .ignorePattern("/System/Library/OnBoardingBundles/"),
      .ignorePattern("/System/Library/OpenDirectory/"),
      .ignorePattern("/System/Library/Perl/"),
      .ignorePattern("/System/Library/PreferenceBundles/"),
      .ignorePattern("/System/Library/PreferencePanes/"),
      .ignorePattern("/System/Library/Printers/"),
      .ignorePattern("/System/Library/PrivateFrameworks/"),
      .ignorePattern("/System/Library/Quicklook/"),
      .ignorePattern("/System/Library/Screen Savers/"),
      .ignorePattern("/System/Library/ScreenReader/"),
      .ignorePattern("/System/Library/Script Editor/"),
      .ignorePattern("/System/Library/ScriptingAdditions/"),
      .ignorePattern("/System/Library/Security/"),
      .ignorePattern("/System/Library/Services/"),
      .ignorePattern("/System/Library/Sounds/"),
      .ignorePattern("/System/Library/Speech/"),
      .ignorePattern("/System/Library/Spotlight/"),
      .ignorePattern("/System/Library/SystemProfiler/"),
      .ignorePattern("/System/Library/Tcl/"),
      .ignorePattern("/System/Library/Templates/"),
      .ignorePattern("/System/Library/TextInput/"),
      .ignorePattern("/System/Library/UserNotifications/"),
      .ignorePattern("/System/iOSSupport"),
      .ignorePattern("/Users/Shared/"),
      .ignorePattern("~/Desktop"),
      .ignorePattern("~/Developer"),
      .ignorePattern("~/Documents"),
      .ignorePattern("~/Downloads"),
      .ignorePattern("~/Dropbox"),
      .ignorePattern("~/Library"),
      .ignorePattern("~/Music"),
      .ignorePattern("~/Pictures"),
      .ignorePattern("~/Public"),
      .ignorePattern("~/Sites")
    ]
  }

  public static func pathExtensions() -> [FileIndexPattern] {
    [
      .ignorePathExtension("bundle"),
      .ignorePathExtension("c"),
      .ignorePathExtension("css"),
      .ignorePathExtension("dylib"),
      .ignorePathExtension("en"),
      .ignorePathExtension("framework"),
      .ignorePathExtension("gif"),
      .ignorePathExtension("h"),
      .ignorePathExtension("html"),
      .ignorePathExtension("jpeg"),
      .ignorePathExtension("jpg"),
      .ignorePathExtension("js"),
      .ignorePathExtension("json"),
      .ignorePathExtension("lock"),
      .ignorePathExtension("lproj"),
      .ignorePathExtension("m"),
      .ignorePathExtension("md"),
      .ignorePathExtension("md"),
      .ignorePathExtension("mm"),
      .ignorePathExtension("pbxproj"),
      .ignorePathExtension("photoslibrary"),
      .ignorePathExtension("playground"),
      .ignorePathExtension("plist"),
      .ignorePathExtension("png"),
      .ignorePathExtension("podspec"),
      .ignorePathExtension("py"),
      .ignorePathExtension("rb"),
      .ignorePathExtension("rtf"),
      .ignorePathExtension("sh"),
      .ignorePathExtension("strings"),
      .ignorePathExtension("svg"),
      .ignorePathExtension("swift"),
      .ignorePathExtension("tif"),
      .ignorePathExtension("trace"),
      .ignorePathExtension("xcassets"),
      .ignorePathExtension("xcodeproj"),
      .ignorePathExtension("xcworkspace"),
      .ignorePathExtension("xib"),
      .ignorePathExtension("yml")
    ]
  }

  public static func lastPathComponents() -> [FileIndexPattern] {
    [
      .ignoreLastPathComponent("Assets"),
      .ignoreLastPathComponent("Caches"),
      .ignoreLastPathComponent("Contents"),
      .ignoreLastPathComponent("Developer"),
      .ignoreLastPathComponent("Gemfile"),
      .ignoreLastPathComponent("LICENSE"),
      .ignoreLastPathComponent("Perl"),
      .ignoreLastPathComponent("PlugIns"),
      .ignoreLastPathComponent("Podfile"),
      .ignoreLastPathComponent("Pods"),
      .ignoreLastPathComponent("Ruby"),
      .ignoreLastPathComponent("Support"),
      .ignoreLastPathComponent("Volumes"),
      .ignoreLastPathComponent("bin"),
      .ignoreLastPathComponent("docs"),
      .ignoreLastPathComponent("dyld"),
      .ignoreLastPathComponent("fastlane"),
      .ignoreLastPathComponent("node_modules"),
      .ignoreLastPathComponent("temp"),
      .ignoreLastPathComponent("tmp"),
      .ignoreLastPathComponent("usr"),
      .ignoreLastPathComponent("xcodegen")
    ]
  }
}
