on:
  pull_request: {}
name: Test
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          xcode: ['14.3']
    steps:
      - name: Set Xcode ${{ matrix.xcode }}
        run: |
          echo "Available Xcode versions:"
          ls /Applications | grep Xcode
          echo "Choosing Xcode_${{ matrix.xcode }}.app"
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
          xcodebuild -version
          swift --version
          swift package --version
      - name: Checkout
        uses: actions/checkout@main
      - name: Install and run xcodegen
        run: |
          brew install tuist
          tuist fetch
          tuist generate -n
      - name: Build and Test
        run: |
          xcodebuild -workspace Keyboard-Cowboy.xcworkspace -scheme "Keyboard-Cowboy" -sdk macosx clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" | xcpretty
