on: pull_request
name: test
jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
        matrix:
          xcode: ['12_beta']
    steps:
      - name: Set Xcode
        run: |
          echo "Available Xcode versions:"
          ls /Applications | grep Xcode
          echo "Choosing Xcode_${{ matrix.xcode }}.app"
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
          xcodebuild -version
          swift --version
          swift package --version
      - name: Checkout
        uses: actions/checkout@main
      - name: Install and run xcodegen
        run: |
          brew install xcodegen
          xcodegen generate
      - name: Build and Text
        run: |
          xcodebuild -project Keyboard-Cowboy.xcodeproj -scheme "Keyboard-Cowboy" -sdk macosx clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED="NO" | xcpretty
