name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Tuist
      run: brew install tuist

    - name: Generate project with Tuist
      run: tuist generate
      continue-on-error: true

    - name: Check for ResultBundle.xcresult
      if: success()
      run: |
        if [ ! -f ResultBundle.xcresult ]; then
          echo "ResultBundle.xcresult not found!"
          exit 1
        fi

    - name: Run tests
      if: success()
      run: kishikawakatsumi/xcresulttool@v1
      with:
        show-passed-tests: true
        show-code-coverage: true
        upload-bundles: always

    - name: Post results
      if: success()
      uses: actions/github-script@v6
      with:
        script: |
          const name = 'Test';
          const url = 'https://github.com/zenangst/KeyboardCowboy/actions/runs/${{ github.run_id }}';
          const success = 'failure' === 'success';
          const body = `${name}: ${success ? 'succeeded ✅' : 'failed ❌'}\n${url}\n\n@zenangst`;
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            body: body
          });
